version: '3.8'

services:

    back:
        build:
            context: backend
            dockerfile: phpdocker/php-fpm/Dockerfile
        container_name: karaoke-back
        working_dir: /application
        volumes:
            - ./backend:/application
            - ./backend/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        expose:
            - 9000

    front:
        build:
            context: frontend
            dockerfile: docker/node/Dockerfile
        container_name: karaoke-front
        working_dir: /application
        expose:
            - 8080

    web:
        image: nginx:alpine
        container_name: karaoke-web
        working_dir: /application
        volumes:
            - ./backend:/application
            - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        expose:
            - 80
        ports:
            - "8080:80"

    base:
        image: mysql:8.3
        command: --default-authentication-plugin=mysql_native_password
        container_name: karaoke-base
        working_dir: /application
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: karaoke-app
            MYSQL_USER: karaoke-app
            MYSQL_PASSWORD: admin
        ports:
            - "33062:3306"
